# Generated by Django 4.0 on 2022-12-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMERCIANTE LOCAL', 'comerciante local'), ('COMERCIANTE EXTRANJERO', 'comerciante extranjero'), ('CONSULTOR', 'consultor'), ('PRODUCTOR', 'productor')], default='COMERCIANTE LOCAL', max_length=30)),
                ('companyName', models.CharField(blank=True, max_length=255)),
                ('initDate', models.DateField(auto_now_add=True)),
                ('modifyDate', models.DateField(auto_now=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('fileName', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
