# Generated by Django 4.0 on 2022-12-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOCAL TRADER', 'local trader'), ('INTERNATIONAL TRADER', 'international trader'), ('CARRIER', 'carrier'), ('PRODUCER', 'producer')], default='LOCAL TRADER', max_length=30)),
                ('companyName', models.CharField(blank=True, max_length=255)),
                ('initDate', models.DateField(auto_now_add=True)),
                ('modifyDate', models.DateField(auto_now=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('fileName', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
