# Generated by Django 4.0 on 2022-11-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=255)),
                ('initDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('archiveName', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
