# Generated by Django 4.0 on 2022-11-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='archiveName',
            new_name='fileName',
        ),
    ]
