# Generated by Django 4.0 on 2022-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_rename_archivename_contrato_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='modifyDate',
            field=models.DateField(auto_now=True),
        ),
    ]
