# Generated by Django 4.0 on 2022-12-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_remove_contract_filename_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
