# Generated by Django 4.0 on 2022-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_contrato_modifydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
