# Generated by Django 4.0 on 2022-11-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_contrato_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='initDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
