# Generated by Django 4.0 on 2022-11-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_alter_contrato_initdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
