# Generated by Django 3.2 on 2022-11-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('postalCode', models.CharField(blank=True, max_length=255)),
                ('productList', models.CharField(blank=True, max_length=255)),
                ('maxAmount', models.IntegerField()),
                ('processStatus', models.CharField(choices=[('Publicada', 'Publicada'), ('Cerrada', 'Cerrada'), ('Adjudicada', 'Adjudicada'), ('Cancelada', 'Cancelada'), ('Rechazada', 'Rechazada')], default='Publicada', max_length=255)),
                ('initDate', models.DateField(auto_now_add=True)),
                ('closeDate', models.DateField()),
            ],
        ),
    ]
