# Generated by Django 4.0 on 2022-12-12 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('comercianteExtranjero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='internationalTrader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.internationaltrader'),
        ),
    ]
