# Generated by Django 4.0 on 2022-11-22 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercianteExtranjero', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitud',
            new_name='Licitacion',
        ),
    ]
