# Generated by Django 4.0 on 2022-11-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('comercianteExtranjero', '0002_rename_solicitud_licitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='extranjero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentas.comercianteextranjero'),
            preserve_default=False,
        ),
    ]
