# Generated by Django 4.0 on 2022-12-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercianteExtranjero', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
