# Generated by Django 4.0 on 2022-11-23 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('comercianteExtranjero', '0003_licitacion_extranjero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='extranjero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.comercianteextranjero'),
        ),
    ]
