# Generated by Django 4.0 on 2022-12-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('ON TRACK', 'On track'), ('FINISHED', 'Finished')], default='PUBLISHED', max_length=255)),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('transport', models.BooleanField(default=True)),
            ],
        ),
    ]
