# Generated by Django 4.0 on 2022-12-14 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('productor', '0001_initial'),
        ('comercianteLocal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingoffer',
            name='localSale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyingoffers', to='productor.localsale'),
        ),
        migrations.AddField(
            model_name='buyingoffer',
            name='localTrader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.localtrader'),
        ),
    ]
