# Generated by Django 4.0 on 2022-12-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercianteLocal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingoffer',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyingoffer',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
