# Generated by Django 4.0 on 2022-12-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0004_localsale_closed_localsale_confirmed'),
        ('comercianteLocal', '0003_buyingoffer_confirmed_buyingoffer_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyingoffer',
            name='producer',
        ),
        migrations.AddField(
            model_name='buyingoffer',
            name='localSale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='productor.localsale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyingoffer',
            name='transport',
            field=models.BooleanField(default=False),
        ),
    ]
