# Generated by Django 4.0 on 2022-12-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0005_localsale_editable_offer_editable'),
        ('comercianteLocal', '0004_remove_buyingoffer_producer_buyingoffer_localsale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyingoffer',
            name='transport',
        ),
        migrations.AddField(
            model_name='buyingoffer',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buyingoffer',
            name='localSale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyingoffers', to='productor.localsale'),
        ),
        migrations.AlterField(
            model_name='buyingoffer',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('ON TRACK', 'On track'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('FINISHED', 'Finished')], default='PUBLISHED', max_length=255),
        ),
    ]
