# Generated by Django 4.0 on 2022-11-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('productorDescription', models.CharField(blank=True, max_length=255)),
                ('offer', models.BooleanField(default=False)),
                ('unitPrice', models.IntegerField()),
                ('adminArchives', models.CharField(blank=True, max_length=255)),
                ('techArchives', models.CharField(blank=True, max_length=255)),
                ('economicArchives', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
