# Generated by Django 4.0 on 2022-11-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_comercianteextranjero_businessname_and_more'),
        ('productor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.productor'),
        ),
        migrations.AlterField(
            model_name='ventalocal',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.productor'),
        ),
    ]
