# Generated by Django 4.0 on 2022-12-12 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsaleimage',
            name='image',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'svg'])]),
        ),
    ]
