# Generated by Django 4.0 on 2022-12-12 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0002_alter_localsaleimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offerFileName',
        ),
        migrations.AddField(
            model_name='offer',
            name='offerFile',
            field=models.FileField(default=None, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
