# Generated by Django 4.0 on 2022-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0002_alter_oferta_productor_alter_ventalocal_productor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventalocal',
            name='vendida',
            field=models.BooleanField(default=False),
        ),
    ]
