# Generated by Django 4.0 on 2022-12-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0002_subastatransporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subastatransporte',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='subastatransporte',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='subastatransporte',
            name='productor',
        ),
    ]
