# Generated by Django 4.0 on 2022-12-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0003_remove_subastatransporte_comprador_and_more'),
        ('transportista', '0004_remove_postulacionlicitaciontransporte_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubastaTransporte',
        ),
    ]
