# Generated by Django 4.0 on 2022-11-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0003_ventalocal_vendida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventalocal',
            old_name='vendida',
            new_name='sold',
        ),
        migrations.RemoveField(
            model_name='ventalocal',
            name='image',
        ),
        migrations.AddField(
            model_name='ventalocal',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'published'), ('HAS_OFFER', 'hasOffer'), ('CLOSED', 'closed')], default='PUBLISHED', max_length=30),
        ),
        migrations.CreateModel(
            name='ImagenVentaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('ventaLocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenventalocal', to='productor.ventalocal')),
            ],
        ),
    ]
