# Generated by Django 4.0 on 2022-11-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0004_rename_vendida_ventalocal_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventalocal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
