# Generated by Django 4.0 on 2022-12-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0004_localsale_closed_localsale_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsale',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
