# Generated by Django 4.0 on 2022-11-30 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercianteExtranjero', '0005_alter_licitacion_closedate_alter_licitacion_initdate'),
        ('cuentas', '0004_delete_metodotransporte'),
        ('productor', '0005_ventalocal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='description',
            new_name='offerDescription',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='unitPrice',
            new_name='offerValue',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='adminArchives',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='economicArchives',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='productorDescription',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='techArchives',
        ),
        migrations.AddField(
            model_name='oferta',
            name='licitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comercianteExtranjero.licitacion'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='offerFileName',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.productor'),
        ),
    ]
