# Generated by Django 4.0 on 2022-11-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0006_rename_description_oferta_offerdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventalocal',
            name='image',
        ),
    ]
