# Generated by Django 4.0 on 2022-11-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0007_remove_ventalocal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenventalocal',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
