# Generated by Django 4.0 on 2022-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0009_alter_imagenventalocal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oferta',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
