# Generated by Django 4.0 on 2022-11-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0010_oferta_accepted_oferta_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='accepted',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'reject'), ('STANDBY', 'standby')], default='STANDBY', max_length=30),
        ),
    ]
