# Generated by Django 3.1.2 on 2022-09-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rut_persona',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Rut'),
        ),
    ]
