# Generated by Django 4.0 on 2022-12-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubastaTransporte',
        ),
    ]
