# Generated by Django 3.1.2 on 2022-09-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('', 'Productor'), ('interno', 'Interno'), ('externproductoro', 'Externo'), ('consultor', 'Consultor'), ('transportista', 'Transportista')], default='externo', max_length=50),
        ),
    ]
