# Generated by Django 3.1.2 on 2022-09-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20220906_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('0', 'Productor'), ('1', 'Interno'), ('2', 'Externo'), ('3', 'Consultor'), ('4', 'Transportista'), ('5', 'Administrador')], default='externo', max_length=50),
        ),
    ]
