# Generated by Django 4.0 on 2022-12-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_delete_subastatransporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cuentas.useraccount')),
            ],
            options={
                'abstract': False,
            },
            bases=('cuentas.useraccount',),
        ),
        migrations.RemoveField(
            model_name='mercancia',
            name='productor',
        ),
        migrations.RemoveField(
            model_name='ventanacional',
            name='mercancia',
        ),
        migrations.RemoveField(
            model_name='ventanacional',
            name='productor',
        ),
        migrations.DeleteModel(
            name='LicitacionInternacional',
        ),
        migrations.DeleteModel(
            name='Mercancia',
        ),
        migrations.DeleteModel(
            name='VentaNacional',
        ),
    ]
