# Generated by Django 4.0 on 2022-11-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercianteextranjero',
            name='businessName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportista',
            name='businessName',
            field=models.CharField(default='OneOff', max_length=50),
            preserve_default=False,
        ),
    ]
