# Generated by Django 4.0 on 2022-11-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_comercianteextranjero_businessname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetodoTransporte',
        ),
    ]
