# Generated by Django 4.0 on 2022-12-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_administrador_remove_mercancia_productor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercianteextranjero',
            name='businessName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='comerciantelocal',
            name='businessName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='businessName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='businessName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Sistema',
        ),
    ]
