# Generated by Django 3.2 on 2022-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_user', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Primer nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('rut', models.CharField(blank=True, max_length=11, verbose_name='RUT')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Direccion')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es administrador')),
                ('tipo_usuario', models.CharField(choices=[('0', 'Externo'), ('1', 'Interno'), ('2', 'Productor'), ('3', 'Transportista'), ('4', 'Consultor'), ('5', 'Administrador')], default='interno', max_length=50, verbose_name='Tipo de usuario')),
                ('country', models.CharField(blank=True, default='Chile', max_length=20, verbose_name='Pais')),
                ('doc_num', models.CharField(blank=True, max_length=9, verbose_name='Numero de documento')),
                ('business_name', models.CharField(blank=True, max_length=100, verbose_name='Razón Social')),
                ('capacity', models.IntegerField(blank=True, default=0, verbose_name='Capacidad de Carga')),
                ('prod_type', models.CharField(blank=True, max_length=150, verbose_name='Tipo de productos')),
                ('size', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Tamaño Transporte')),
                ('cooling', models.BooleanField(blank=True, default=False, verbose_name='Refrigeración')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
