# Generated by Django 3.1.2 on 2022-09-03 17:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut_persona', models.CharField(max_length=20)),
                ('telefono_contacto', models.CharField(max_length=25)),
                ('fec_emision_contrato', models.DateField(blank=True, default=datetime.date(2022, 9, 3))),
                ('fec_fin_contrato', models.DateField(blank=True, default=datetime.date(2023, 9, 3))),
                ('estado', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
