# Generated by Django 4.0 on 2022-12-12 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('comercianteExtranjero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportPostulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=255)),
                ('cooling', models.BooleanField(default=False)),
                ('postDate', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('accepted', models.CharField(choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('STANDBY', 'standby')], default='STANDBY', max_length=30)),
                ('closed', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('bid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='postulations', to='comercianteExtranjero.bid')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PREPARATION', 'preparation'), ('AWAITING_CARRIER', 'awaiting carrier'), ('RECEIVED_BY_CARRIER', 'received by carrier'), ('ON_TRACK', 'on track'), ('RECEPTIONED', 'receptioned')], default='PREPARATION', max_length=30)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comercianteExtranjero.bid')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.carrier')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.producer')),
            ],
        ),
    ]
