# Generated by Django 4.0 on 2022-12-01 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('comercianteExtranjero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionLicitacionTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=255)),
                ('size', models.IntegerField(null=True)),
                ('cooling', models.BooleanField(default=False)),
                ('postDate', models.DateField(auto_now_add=True)),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comercianteExtranjero.licitacion')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.transportista')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.transportista')),
            ],
        ),
    ]
