# Generated by Django 4.0 on 2022-11-30 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercianteExtranjero', '0005_alter_licitacion_closedate_alter_licitacion_initdate'),
        ('cuentas', '0004_delete_metodotransporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionLicitacionTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDate', models.DateField(auto_now_add=True)),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comercianteExtranjero.licitacion')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.transportista')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.transportista')),
            ],
        ),
    ]
