# Generated by Django 4.0 on 2022-12-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transportpostulation',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
