# Generated by Django 4.0 on 2022-12-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0002_subastatransporte'),
        ('transportista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacionlicitaciontransporte',
            name='licitacion',
        ),
        migrations.AddField(
            model_name='postulacionlicitaciontransporte',
            name='subasta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='productor.subastatransporte'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MetodoTransporte',
        ),
    ]
