# Generated by Django 4.0 on 2022-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0002_remove_postulacionlicitaciontransporte_licitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionlicitaciontransporte',
            name='accepted',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('STANDBY', 'standby')], default='STANDBY', max_length=30),
        ),
        migrations.AddField(
            model_name='postulacionlicitaciontransporte',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postulacionlicitaciontransporte',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postulacionlicitaciontransporte',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
