# Generated by Django 4.0 on 2022-12-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercianteExtranjero', '0002_initial'),
        ('transportista', '0003_postulacionlicitaciontransporte_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacionlicitaciontransporte',
            name='size',
        ),
        migrations.RemoveField(
            model_name='postulacionlicitaciontransporte',
            name='subasta',
        ),
        migrations.AddField(
            model_name='postulacionlicitaciontransporte',
            name='licitacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='comercianteExtranjero.licitacion'),
        ),
        migrations.AlterField(
            model_name='postulacionlicitaciontransporte',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
