# Generated by Django 4.0 on 2022-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportista', '0005_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionlicitaciontransporte',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='envio',
            name='status',
            field=models.CharField(choices=[('PREPARATION', 'preparation'), ('AWAITING_CARRIER', 'awaiting carrier'), ('RECEIVED_BY_CARRIER', 'received by carrier'), ('ON_TRACK', 'on track'), ('RECEPTIONED', 'receptioned')], default='PREPARATION', max_length=30),
        ),
    ]
