# Generated by Django 3.2 on 2022-09-11 08:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_ped', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descrip', models.CharField(max_length=200)),
                ('estado_admin', models.BooleanField(default=False)),
                ('estado_productor', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='ProcesPedido',
            fields=[
                ('id_proc_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado_proceso', models.BooleanField(default=False)),
                ('pedido_id_ped', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.pedido')),
            ],
            options={
                'verbose_name': 'ProcesPedido',
                'verbose_name_plural': 'ProcesosPedidos',
                'db_table': 'ProcesPedido',
            },
        ),
        migrations.CreateModel(
            name='ProcesVenta',
            fields=[
                ('id_proc_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('proces_pedido_id_proc_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procespedido')),
            ],
            options={
                'verbose_name': 'ProcesVenta',
                'verbose_name_plural': 'ProcesosVenta',
                'db_table': 'ProcesVenta',
            },
        ),
        migrations.CreateModel(
            name='VentLocal',
            fields=[
                ('id_vent_loc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=20)),
                ('ape_pat', models.CharField(max_length=20)),
                ('ape_mat', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('proces_venta_id_proc_venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procesventa')),
            ],
            options={
                'verbose_name': 'VentLocal',
                'verbose_name_plural': 'VentasLocales',
                'db_table': 'VentLocal',
            },
        ),
        migrations.CreateModel(
            name='VentExtran',
            fields=[
                ('id_vent_ex', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=20)),
                ('ape_pat', models.CharField(max_length=20)),
                ('ape_mat', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('proces_venta_id_proc_venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procesventa')),
            ],
            options={
                'verbose_name': 'VentExtran',
                'verbose_name_plural': 'VentasExtranjeras',
                'db_table': 'VentExtran',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_trans', models.AutoField(primary_key=True, serialize=False)),
                ('tip_transporte', models.CharField(max_length=15)),
                ('tamano_trans', models.IntegerField()),
                ('capacidad_trans', models.IntegerField()),
                ('refrigeracion_trans', models.CharField(max_length=10)),
                ('fecha_trans', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'db_table': 'Transporte',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('est_seguimiento', models.CharField(choices=[('preparando', 'preparando productos'), ('despacho', 'productos despachados'), ('recepcionados', 'recepcionados por el transportista'), ('viaje', 'en camino'), ('completado', 'seguimiento finalizado')], default='preparando', max_length=50)),
                ('pedido_id_ped', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.pedido')),
                ('proces_pedido_id_proc_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procespedido')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimiento',
                'db_table': 'Seguimiento',
            },
        ),
        migrations.CreateModel(
            name='ReportVenta',
            fields=[
                ('id_report_vent', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_venta', models.CharField(max_length=20)),
                ('cant_venta', models.IntegerField()),
                ('total_venta', models.IntegerField()),
                ('proces_venta_id_proc_venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procesventa')),
            ],
            options={
                'verbose_name': 'ReportVenta',
                'verbose_name_plural': 'ReportesVentas',
                'db_table': 'ReportVenta',
            },
        ),
        migrations.CreateModel(
            name='ReportMerma',
            fields=[
                ('id_merma', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_merma', models.DateField()),
                ('descrip_merma', models.CharField(max_length=40)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ReportMerma',
                'verbose_name_plural': 'ReportesMermas',
                'db_table': 'ReportMerma',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_report', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_report', models.DateField()),
                ('tip_report', models.CharField(max_length=15)),
                ('user_report', models.CharField(max_length=15)),
                ('descrip_report', models.CharField(max_length=30)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reportes',
                'verbose_name_plural': 'Reportes',
                'db_table': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=20)),
                ('precio_prod', models.IntegerField()),
                ('desc_prod', models.CharField(max_length=200)),
                ('stock_prod', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.AddField(
            model_name='procespedido',
            name='transporte_id_trans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.transporte'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos_id_prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.productos'),
        ),
        migrations.CreateModel(
            name='DirecLocal',
            fields=[
                ('id_direc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('direc_cli', models.CharField(max_length=20)),
                ('num_calle', models.IntegerField(blank=True, null=True)),
                ('depto', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(max_length=20)),
                ('comuna', models.CharField(max_length=20)),
                ('vent_local_id_vent_loc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.ventlocal')),
            ],
            options={
                'verbose_name': 'DirecLocal',
                'verbose_name_plural': 'DireccionesLocales',
                'db_table': 'DirecLocal',
            },
        ),
        migrations.CreateModel(
            name='DirecExtran',
            fields=[
                ('id_direc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=20)),
                ('direc_cli', models.CharField(max_length=20)),
                ('num_calle', models.IntegerField(blank=True, null=True)),
                ('depto', models.CharField(blank=True, max_length=10, null=True)),
                ('localidad', models.CharField(max_length=20)),
                ('vent_extran_id_vent_ex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.ventextran')),
            ],
            options={
                'verbose_name': 'DirecExtran',
                'verbose_name_plural': 'DireccionesExtranjeras',
                'db_table': 'DirecExtran',
            },
        ),
        migrations.CreateModel(
            name='DetallCompra',
            fields=[
                ('id_detall', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_detall', models.DateField()),
                ('nom_producto', models.CharField(max_length=15)),
                ('cost_producto', models.IntegerField()),
                ('iva_producto', models.IntegerField()),
                ('total_compra', models.IntegerField()),
                ('proces_venta_id_proc_venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procesventa')),
            ],
            options={
                'verbose_name': 'DetallCompra',
                'verbose_name_plural': 'DetallesCompras',
                'db_table': 'DetallCompra',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_persona', models.CharField(max_length=20)),
                ('telefono_contacto', models.CharField(max_length=25)),
                ('fec_emision_contrato', models.DateField(blank=True, default=datetime.date(2022, 9, 11))),
                ('fec_fin_contrato', models.DateField(blank=True, default=datetime.date(2023, 9, 11))),
                ('estado', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
